export const ModeEnum = {
  FREE_TEXT: 'FREE_TEXT',
  SELECTION_ONLY: 'SELECTION_ONLY',
}

export const CardinalityEnum = {
  SINGLE: 'SINGLE',
  MULTI: 'MULTI',
}

export const ConditionEnum = {
  1000: 'NEW',
  2750: 'LIKE_NEW',
  1500: 'NEW_OTHER',
  1750: 'NEW_WITH_DEFECTS',
  2000: 'CERTIFIED_REFURBISHED',
  2010: 'EXCELLENT_REFURBISHED',
  2020: 'VERY_GOOD_REFURBISHED',
  2030: 'GOOD_REFURBISHED',
  2500: 'SELLER_REFURBISHED',
  3000: 'USED_EXCELLENT',
  4000: 'USED_VERY_GOOD',
  5000: 'USED_GOOD',
  6000: 'USED_ACCEPTABLE',
  7000: 'FOR_PARTS_OR_NOT_WORKING',
}

// ConditionEnum反过来
export const ConditionEnumReverse = {
  NEW: 1000,
  LIKE_NEW: 2750,
  NEW_OTHER: 1500,
  NEW_WITH_DEFECTS: 1750,
  CERTIFIED_REFURBISHED: 2000,
  EXCELLENT_REFURBISHED: 2010,
  VERY_GOOD_REFURBISHED: 2020,
  GOOD_REFURBISHED: 2030,
  SELLER_REFURBISHED: 2500,
  USED_EXCELLENT: 3000,
  USED_VERY_GOOD: 4000,
  USED_GOOD: 5000,
  USED_ACCEPTABLE: 6000,
  FOR_PARTS_OR_NOT_WORKING: 7000,
}

export const AspectDataTypeEnum = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  STRING_ARRAY: 'STRING_ARRAY',
}

// 刊登类型
export const ListingTypeEnum = {
  FIXED_PRICE: 'FIXED_PRICE',
  AUCTION: 'AUCTION',
}

export const AvailabilityType = {
  IN_STOCK: 'IN_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',

}

export const EbayProductStatus = {
  NOT_PUBLISH: 'NOT_PUBLISH',
  PUBLISH: 'PUBLISH',
}